AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  RegionEqualsEastOne: !Equals [!Ref 'AWS::Region', us-east-1]
Description: Creates the database for use by the Cerberus Management Service (CMS)
Outputs:
  cmsDbAddress:
    Value: !GetAtt 'CmsDatabaseCluster.Endpoint.Address'
  cmsDbId:
    Value: !Ref 'CmsDbInstance'
  cmsDbJdbcConnectionString:
    Description: JDBC connection string for cms database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt 'CmsDbInstance.Endpoint.Address', ':',
        !GetAtt 'CmsDatabaseCluster.Endpoint.Port', /, !Ref 'cmsDbName', '?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC']]
Parameters:
  cmsDbInstanceSize:
    Default: db.r3.large
    Description: MySQL DB instance class
    Type: String
  cmsDbMasterPassword:
    Description: Master password for the cms RDS instance
    Type: String
    NoEcho: true
  cmsDbMasterUsername:
    Description: Master username for the cms RDS instance
    Type: String
  cmsDbName:
    Description: The name of the database initially create on the RDS instance
    Type: String
  cmsDbPrimaryAz:
    AllowedPattern: '[a-z]{2}-[a-z]+-\d\w'
    Description: The availability zone for the primary CMS DB Instance
    Type: String
  cmsDbReplicaAz:
    AllowedPattern: '[a-z]{2}-[a-z]+-\d\w'
    Description: The availability zone for the standby read replica CMS DB Instance
    Type: String
  sgStackName:
    Description: The name of the Cerberus Security Groups CloudFormation stack
    Type: String
  tagClassification:
    Default: Gold
    Description: Denotes which category of Data Classification the instance is grouped
      under.
    Type: String
  tagCostcenter:
    Description: Represents the Cost Center associated with the team/project.aaa
    Type: String
  tagEmail:
    Description: E-mail address for group or person responsible for the stack.
    Type: String
  tagName:
    Description: 'Environment name, e.g. "cerberus-{environment}"'
    Type: String
  vpcSubnetIdForAz1:
    Description: The subnet for the first availability zone
    Type: String
  vpcSubnetIdForAz2:
    Description: The subnet for the second availability zone
    Type: String
  vpcSubnetIdForAz3:
    Description: The subnet for the third availability zone
    Type: String
Resources:
  CmsDatabaseCluster:
    Properties:
      AvailabilityZones:
        - Ref: 'cmsDbPrimaryAz'
        - Ref: 'cmsDbReplicaAz'
      BackupRetentionPeriod: 14
      DatabaseName: !Ref 'cmsDbName'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      MasterUserPassword: !Ref 'cmsDbMasterPassword'
      MasterUsername: !Ref 'cmsDbMasterUsername'
      Port:
        Fn::ImportValue: !Sub "${sgStackName}-cmsDbPort"
      PreferredBackupWindow: 13:14-13:44
      PreferredMaintenanceWindow: tue:06:48-tue:07:18
      StorageEncrypted: 'true'
      Tags:
        - Key: Name
          Value: !Ref 'tagName'
        - Key: email
          Value: !Ref 'tagEmail'
        - Key: classification
          Value: !Ref 'tagClassification'
        - Key: costcenter
          Value: !Ref 'tagCostcenter'
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${sgStackName}-cmsDbSgId"
    Type: AWS::RDS::DBCluster
  CmsDbInstance:
    Properties:
      DBClusterIdentifier: !Ref CmsDatabaseCluster
      DBInstanceClass: !Ref 'cmsDbInstanceSize'
      DBParameterGroupName: !Ref 'CmsDatabaseParamGroup'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      PubliclyAccessible: 'false'
    Type: AWS::RDS::DBInstance
  # There is no guarantee that this instance will be the read replica, since
  # RDS decides automatically
  CmsReadReplicaDbInstance:
    Properties:
      DBClusterIdentifier: !Ref CmsDatabaseCluster
      DBInstanceClass: !Ref 'cmsDbInstanceSize'
      DBParameterGroupName: !Ref 'CmsDatabaseParamGroup'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      PubliclyAccessible: 'false'
    Type: AWS::RDS::DBInstance
  CmsDatabaseParamGroup:
    Properties:
      Description: Default parameters for the cms DB
      Family: aurora5.6
      Parameters:
        log_output: TABLE
        slow_query_log: 1
    Type: AWS::RDS::DBParameterGroup
  CmsDatabaseSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for management DB
      SubnetIds:
        - Ref: 'vpcSubnetIdForAz1'
        - Ref: 'vpcSubnetIdForAz2'
        - Ref: 'vpcSubnetIdForAz3'
    Type: AWS::RDS::DBSubnetGroup
  