AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  RegionEqualsEastOne: !Equals [!Ref 'AWS::Region', us-east-1]
Description: Creates the database for use by the Cerberus Management Service (CMS)
Outputs:
  cmsDbAddress:
    Value: !GetAtt 'CmsDatabaseCluster.Endpoint.Address'
  cmsDbInstanceId1:
    Value: !Ref 'CmsDbInstance1'
  cmsDbInstanceId2:
    Value: !Ref 'CmsDbInstance2'
  cmsDbJdbcConnectionString:
    Description: JDBC connection string for cms database
    Value: !Join ['', ['jdbc:mysql://', !GetAtt 'CmsDatabaseCluster.Endpoint.Address', ':',
        !GetAtt 'CmsDatabaseCluster.Endpoint.Port', /, !Ref 'cmsDbName', '?useUnicode=true&characterEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=UTC']]
Parameters:
  cmsDbInstanceAz1:
    Default: 'us-west-2a'
    AllowedPattern: '[a-z]{2}-[a-z]+-\d\w'
    Description: The first availability zone for the DB Instances
    Type: String
  cmsDbInstanceAz2:
    Default: 'us-west-2b'
    AllowedPattern: '[a-z]{2}-[a-z]+-\d\w'
    Description: The second availability zone for the DB Instances
    Type: String
  cmsDbInstanceAz3:
    Default: 'us-west-2b'
    AllowedPattern: '[a-z]{2}-[a-z]+-\d\w'
    Description: The third availability zone for the DB Instances
    Type: String
  cmsDbInstanceSize:
    Default: db.r3.large
    Description: MySQL DB instance class
    Type: String
  cmsDbMasterPassword:
    Description: Master password for the cms RDS instance
    Type: String
    NoEcho: true
  cmsDbMasterUsername:
    Default: 'cms'
    Description: Master username for the cms RDS instance
    Type: String
  cmsDbName:
    Default: 'cms'
    Description: The name of the database initially create on the RDS instance
    Type: String
  sgStackName:
    Description: The name of the Cerberus Security Groups CloudFormation stack
    Type: String
  vpcSubnetIdForAz1:
    Description: The subnet for the first availability zone
    Type: String
  vpcSubnetIdForAz2:
    Description: The subnet for the second availability zone
    Type: String
  vpcSubnetIdForAz3:
    Description: The subnet for the third availability zone
    Type: String
Resources:
  CmsDatabaseCluster:
    Properties:
      AvailabilityZones:
        - Ref: 'cmsDbInstanceAz1'
        - Ref: 'cmsDbInstanceAz2'
        - Ref: 'cmsDbInstanceAz3'
      BackupRetentionPeriod: 14
      DatabaseName: !Ref 'cmsDbName'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      MasterUserPassword: !Ref 'cmsDbMasterPassword'
      MasterUsername: !Ref 'cmsDbMasterUsername'
      Port:
        Fn::ImportValue: !Sub "${sgStackName}-cmsDbPort"
      PreferredBackupWindow: 13:14-13:44
      PreferredMaintenanceWindow: tue:06:48-tue:07:18
      StorageEncrypted: 'true'
      VpcSecurityGroupIds:
        - Fn::ImportValue: !Sub "${sgStackName}-cmsDbSgId"
    Type: AWS::RDS::DBCluster
  # Create two DB instances one primary/write instance and the other a read replica.
  # The Aurora CloudFormation does not let you choose which is read or write.
  # Aurora decides automatically for you behind the scenes.
  CmsDbInstance1:
    Properties:
      DBClusterIdentifier: !Ref CmsDatabaseCluster
      DBInstanceClass: !Ref 'cmsDbInstanceSize'
      DBParameterGroupName: !Ref 'CmsDatabaseParamGroup'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      PubliclyAccessible: 'false'
    Type: AWS::RDS::DBInstance
  CmsDbInstance2:
    Properties:
      DBClusterIdentifier: !Ref CmsDatabaseCluster
      DBInstanceClass: !Ref 'cmsDbInstanceSize'
      DBParameterGroupName: !Ref 'CmsDatabaseParamGroup'
      DBSubnetGroupName: !Ref 'CmsDatabaseSubnetGroup'
      Engine: aurora
      PubliclyAccessible: 'false'
    Type: AWS::RDS::DBInstance
  CmsDatabaseParamGroup:
    Properties:
      Description: Default parameters for the cms DB
      Family: aurora5.6
      Parameters:
        log_output: TABLE
        slow_query_log: 1
    Type: AWS::RDS::DBParameterGroup
  CmsDatabaseSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DB Subnet Group for management DB
      SubnetIds:
        - Ref: 'vpcSubnetIdForAz1'
        - Ref: 'vpcSubnetIdForAz2'
        - Ref: 'vpcSubnetIdForAz3'
    Type: AWS::RDS::DBSubnetGroup
  