AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the necessary S3 buckets, and KMS CMKs for Cerberus
Outputs:
  configBucketDomainName:
    Value: !GetAtt 'CerberusConfigBucket.DomainName'
  configBucketName:
    Value: !Ref 'CerberusConfigBucket'
  environmentDataKmsCmkArn:
    Value: !GetAtt 'EnvironmentDataKmsCmk.Arn'
  cmsSecureDataKmsCmkArn:
    Value: !GetAtt 'CmsSecureDataKmsCmk.Arn'
Parameters:
  cmsIamRoleArn:
    Description: The ARN for for the management service IAM Role.
    Type: String
  accountAdminArn:
    Description: The ARN for a IAM user, group or role that can create this stack.
    Type: String
Resources:
  CerberusConfigBucket:
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket
  CerberusConfigBucketAccessPolicy:
    Properties:
      Bucket: !Ref 'CerberusConfigBucket'
      PolicyDocument:
        Statement:
          - Action:
              - s3:ListBucket
            Effect: Allow
            Principal:
              AWS:
                !Ref 'cmsIamRoleArn'
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket']]
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket', /*]]
            Sid: Allow-ListBucket-Access
          - Action:
              - s3:*
            Effect: Allow
            Principal:
              AWS:
                !Ref 'cmsIamRoleArn'
            Resource:
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket', /certificates/*]]
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket', /certificates]]
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket', /cms/*]]
              - !Join ['', ['arn:aws:s3:::', !Ref 'CerberusConfigBucket', /cms]]
            Sid: Allow-Bucket-Access-For-CMS
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
  EnvironmentDataKmsCmk:
    Properties:
      Description: Cerberus encryption key for storing config files in an encrypted
        state.
      Enabled: 'true'
      KeyPolicy:
        Statement:
          - Action:
              - kms:*
            Effect: Allow
            Principal:
              AWS:
                - !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':root']]
            Resource: '*'
            Sid: Allow-Root-User
          - Action:
              - kms:Decrypt
            Effect: Allow
            Principal:
              AWS:
                - !Ref 'cmsIamRoleArn'
            Resource: '*'
            Sid: Allow-Decrypt-From-Instances
          - Action:
              - kms:*
            Effect: Allow
            Principal:
              AWS:
                !Ref 'accountAdminArn'
            Resource: '*'
            Sid: Allow-Account-Admin
        Version: '2012-10-17'
    Type: AWS::KMS::Key
  CmsSecureDataKmsCmk:
    Properties:
      Description: CMS KMS CMK for storing secure data in RDS.
        state.
      Enabled: 'true'
      KeyPolicy:
        Statement:
          - Action:
              - kms:*
            Effect: Allow
            Principal:
              AWS:
                - !Join ['', ['arn:aws:iam::', !Ref 'AWS::AccountId', ':root']]
            Resource: '*'
            Sid: Allow-Root-User
          - Action:
              - kms:Decrypt
            Effect: Allow
            Principal:
              AWS:
                - !Ref 'cmsIamRoleArn'
            Resource: '*'
            Sid: Allow-Decrypt-From-Instances
          - Action:
              - kms:*
            Effect: Allow
            Principal:
              AWS:
                !Ref 'accountAdminArn'
            Resource: '*'
            Sid: Allow-Account-Admin
        Version: '2012-10-17'
    Type: AWS::KMS::Key